# Generated by Django 5.0.6 on 2024-06-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapefilemodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
